### ISSUE TITLE
not running 

### ISSUE THREAD

**Issue by achdark** [WeebSec/PhishX#1]
Traceback (most recent call last):
  File "PhishX.py", line 32, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay

**Comment by achdark** [comment]
i already try it but 
not working

**Comment by zanyarjamal** [comment]
its either you didn't run both the **installer.sh** and the **PhishX.py** by the root user or some error happened during the installation...   , anyways here this should fix it
 `$ pip3 install pyvirtualdisplay`

**Comment by MR-Sploit** [comment]
start it with python3

python3 PhishX.py
