### ISSUE TITLE
Code cleanup: Keep it DRY

### ISSUE THREAD

**Issue by 5kyc0d3r** [WeebSec/PhishX#2]
https://github.com/WeebSec/PhishX/blob/88701bd14ed618728bed796fad606a8f7adb9e5e/PhishX.py#L101-L106

I would recommend creating a function for printing your menu entries.
This example uses the new in Python 3 fstrings: https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

So your function would become something like this:
```python
def print_entry(entry_name, entry=0):
    print(f'\t{Grey}[{Blue}{entry}{Grey}]-[{Green}{entry_name}{Grey}]')
```

You can create a list with your entries
```
['Twitter', 'Facebook', ...]
```
and iterate over them to print your menu entries with numbers:
```python
menu_entry_list = ['Twitter', 'Facebook', ...]

for num, entry_name in enumerate(menu_entry_list, start=1):
    print_entry(entry_name, entry=num)
```

**Comment by zanyarjamal** [comment]
Thx I fixed my mess  :+1:
