### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Athulath** [WeebSec/PhishX#30]
its showing this error while it try to open

./PhishX.py
./PhishX.py: line 25: import: command not found
./PhishX.py: line 31: syntax error near unexpected token `!='
./PhishX.py: line 31: `if os.geteuid() != 0:'
$

**Comment by LulzsecHackz** [comment]
open with `python3 PhishX.py` noobs

**Comment by Athulath** [comment]
will you please provide the start to end commands to fix all the issue

**Comment by Athulath** [comment]
i got the command to fix thia issue jus type
python3 PhishX.py
