### ISSUE TITLE
Try to open phishx.py and this error happends File "PhishX.py", line 586 SyntaxError: Non-ASCII character '\xef' in file PhishX.py on line 587, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by Logan-Purcell** [WeebSec/PhishX#52]

**Comment by whosdaiz** [comment]
run using python3

**Comment by LulzsecHackz** [comment]
apt-get install python3.7
Or download from internet the package and install it for ur OS... AND THEN run with. `python3.7 PhishX.py`
Or `` python3 PhishX.py ``

**Comment by Parshuram2** [comment]
> apt-get install python3.7
> Or download from internet the package and install it for ur OS... AND THEN run with. `python3.7 PhishX.py`
> Or `python3 PhishX.py`

Dude..did you get the emails working?..I am using gmail smtp. It sends out the test e-mails and I recieve it. It does not send out the phishing e-mails. There is also no way to see what error is happening. Any ideas?
