### ISSUE TITLE
No Such File or Directory base/gecko

### ISSUE THREAD

**Issue by Parshuram2** [WeebSec/PhishX#58]
Did any of you guys get this error?? the sms window does not open when attack launched. I tried running it from within the directory.

**Comment by ArunDinfinity** [comment]
Me too same happened did u fix? 
Also I try to run from the sms_support folder but didn't work throws an error 
info=open('sms_support/phone',r)

**Comment by Parshuram2** [comment]
Delete the "sms_support" part. It will work.
Should be open("phone",r)

**Comment by ArunDinfinity** [comment]
U mean to delete Sms_support from Phishx directory??

**Comment by Parshuram2** [comment]
No man. Delete the "sms_support" from the code. "info= ('phone',r)"..That's
how the code should like....Open PhishX.py in leafpad. CTRF type
"sms_support" then delete it.

**Comment by ArunDinfinity** [comment]
Got it man after I read again
Also I told you that yesterday the email was sending but after it send one mail now it's not sending anymore ,I checked the SMTP and it says error 550 verification failed error 
Recipient is rejecting etc
I tried to change smtpGo to send grid SMTP and it's shows the same error now

**Comment by Parshuram2** [comment]
If you are using sendgrid, port should be 25 because "tls=no". Other ports
need TLS verification.

**Comment by ArunDinfinity** [comment]
Thx man you know lot of stuffs and I have used 587 maybe it's cuz of that also I added that line into the phisx python script after watching a Indonesia guy video "TLS=no"

**Comment by ArunDinfinity** [comment]
Now I get the same error u had no such file or directory base/gecodriver

**Comment by Parshuram2** [comment]
Copy geckodriver in /use/local/bin. "base/geckodriver" remove "base" from
this in the code. Just 'geckodriver'.

**Comment by ArunDinfinity** [comment]
that one solved now its raising new expections:

Traceback (most recent call last):
  File "facebook_sms.py", line 70, in <module>
    br = webdriver.Firefox(firefox_binary=binary,executable_path='geckodriver',firefox_profile=profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Parshuram2** [comment]
are you running facebook_sms.py directly? That will not work. If not just
check the versions of gecko,firefox and selenium. go inside the base folder
on command prompt and type "firefox --version" to confirm it is 60 or
above. Btw you don't need to send sms because the victim has no place to
enter the sms sent. if anything, he will end up on the real site.

**Comment by ArunDinfinity** [comment]
I tried both when I try directly I got the error but when I try otherwise I get nothing I mean no msg to my phone.
After I check version ,mine is 65.0.1
Also thank you man after I used port 25 it's working very will I mean I told u before that there was a 550 verification failed error ,even though both 25 and 587 are TLS connection idk why it's not going through 587 but on 25 perfectly also I received mail
But it's I only receiving the mail when I check the mail status in the check options .
But not from Facebook, Instagram and other options why??how to solve it

**Comment by Parshuram2** [comment]
I have posted solution to all problems in a new post opened as an issue.
https://github.com/WeebSec/PhishX/issues read the first issue.
