### ISSUE TITLE
someone fucks someone right here:- browser.get("http://localhost:4040/status")

### ISSUE THREAD

**Issue by Parshuram2** [WeebSec/PhishX#62]
The program gets stuck here. I don't know who is fucking who..selenium or firefox or geckodriver..someone is fucking the other and the motherfucking cocksucker program won't motherfucking run.  I did pdb the son of a bitch and it clearly motherfucking shows that the sumbitch can't open or connect to the motherfucking firefox browser like the dirty fuck is supposed to.

**Comment by zanyarjamal** [comment]
git gewd scrub

**Comment by Parshuram2** [comment]
> git gewd scrub

You, Sir are an interloper. Urinate off.

**Comment by zanyarjamal** [comment]
am the dev...

**Comment by Parshuram2** [comment]
> am the dev...

??...Really...Never ever seen you around here. Lol.

**Comment by Parshuram2** [comment]
gecko:- 0.18.0 Firefox 60.6.1 selenium 3.5.2 ...what is wrong here? ...browser.get simply times out.  If you are the dev..I'm sure you can tell me which one is the wrong verison? I am guessing firefox...Do I need to downgrade it?

**Comment by Parshuram2** [comment]
geckodriver's log 
addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
