### ISSUE TITLE
help

### ISSUE THREAD

**Issue by drrahulravi** [WeebSec/PhishX#7]
File "PhishX.py", line 42, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'

**Comment by sufyanarain** [comment]
zanyarjamal
please give me solution of this error,,
Traceback (most recent call last):
  File "PhishX.py", line 42, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
