### ISSUE TITLE
Issue with Kali 2018

### ISSUE THREAD

**Issue by FredHilbert** [WeebSec/PhishX#9]
Hi,
Thank you for you Youtube channel, I'm a big fan.
I've a problem after installing `bash installer.sh` the fist error message say pyvirtualdisplay is missing. Then I solve the problem with `pip install pyvirtualdisplay`. Same thing with selenium.
And then I've this message :
![image](https://user-images.githubusercontent.com/16060531/45749807-2835a080-bc0d-11e8-9346-fa184832f06d.png)
Do you have an idea to solve it ?

**Comment by zanyarjamal** [comment]
hello, first you'll have to check if your apt-get is fine, try installing a package:

```bash
$ apt-get install xvfb
```

if it gave any sort of errors, you'll have to fix it before and then run the installer again + PhishX is coded in python 3  so run it with python3

**Comment by FredHilbert** [comment]
apt-get is fine.

I've already try `$ apt-get install xvfb` as I see here on issue https://github.com/WeebSec/PhishX/issues/7 

I've try also on a KALI 2017.1 but I've the same problem.

**Comment by akshay-ken** [comment]
just go to that mentioned line in mentioned dir then you will understand

**Comment by FredHilbert** [comment]
> just go to that mentioned line in mentioned dir then you will understand

**Comment by FredHilbert** [comment]
> > just go to that mentioned line in mentioned dir then you will understand

Thank you akshay-ken, I've already take a look into /root/PhishX/data/twitter.py but I've this error on all . or @ or other normal character.

I've a Luxembourgish keyboard set in KALI, is that a problem for this script ?

![image](https://user-images.githubusercontent.com/16060531/45776226-8d5fb500-bc52-11e8-9d66-2656fd174f51.png)

**Comment by zanyarjamal** [comment]
@FredHilbert like i said above, run it with python3 like this:

```bash
$ python3 PhishX.py
```

**Comment by FredHilbert** [comment]
sorry for the misunderstanding. But even with python3 I have this error.

I've now deleted all é, ô, ç, etc and it work.

I test tomorrow on another computer. I'm on Virtualbox for the moment.

Thank you for you patience :-)

**Comment by LulzsecHackz** [comment]
lmfao use Atom or Visual Studio Code and search for characters...
